version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  init:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv .capstone
            source .capstone/bin/activate
            make install
      - save_cache:
          paths:
            - ./.capstone  # TODO: Include in cache the "bin" directory
          key: v1-dependencies-{{ checksum "app/requirements.txt" }}
      - run:
          name: Run lint
          command: |
            source .capstone/bin/activate
            make lint 


workflows:
  default:
    jobs:
      - init        
      - docker/publish:
          matrix:
            parameters:
              image: [$DOCKER_LOGIN/app]
              path: [app]
              docker-context: [app]
              deploy: [true]
              # We publish two images with different version tags: 
              # - numbered version
              # - "latest"
              # tag: ['$(<app/VERSION.txt)-${CIRCLE_SHA1:0:7}', 'latest']
              tag: ['$(<app/VERSION.txt)', 'latest']
              update-description: [true]    
          requires: [init]
